### ISSUE TITLE
Prevents text selection in live preview

### ISSUE THREAD

**Issue by huachuman** [Krusty84/obsidian-occura-plugin#3] opened 2024-11-01 22:23 UTC
When occura is enabled and I select text (e.g. a whole paragraph), it immediately deselects. 

disabling occura fixes the problem.

obsidian 1.7.4 windows 11

**Comment by Krusty84** [comment] 2024-11-02 14:12
Hello @huachuman I will try to check, cause I don't have win 11, I have checked it on MacOS and 1.7.4 and I was not able to reproduce this behavior:(

**Comment by Krusty84** [comment] 2024-11-05 09:33
@huachuman Could you please make a demo movie with the problem?

**Comment by Krusty84** [comment] 2024-11-13 09:37
I will close the issue, if you will be ready to provide more data about problem, please reopen IR

**Closed as completed by Krusty84** 2024-11-13 09:37 UTC
